server:
  port: 9091

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: WEATHER-PREDICTION-API
          uri: lb://WEATHER-PREDICTION-API
          predicates:
            - Path=/weather/v1/prediction/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
